service: twitter-dad-jokes

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-mocha-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
  serverless-offline:
    port: 3000
    host: 0.0.0.0

provider:
  name: aws
  runtime: nodejs8.10
  region: ${file(./.env.yml):REGION}
  environment: ${file(./.env.yml)}

functions:
  dadJoke:
    handler: handlers/twitter.dadJoke
    events:
       - schedule:
          name: dad-jokes
          rate: rate(1 hour)
